version: '2'
services:
  spring-web:
    build: .
  ha-proxy:
    image: dockercloud/haproxy
    links:
      - spring-web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80