version: '2'
services:
  spring-web:
    depends_on:
      - redis
    image: thomptr/dockerdemo
    links:
      - redis
#    build: .
  redis:
    image: redis:3.2
    hostname: redis
    ports:
      - "6379:6379"
  ha-proxy:
    image: dockercloud/haproxy
    links:
      - spring-web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80