version: '2'
services:
  spring-web:
    depends_on:
      - redis
      - mysql
    image: thomptr/dockerdemo
    links:
      - redis
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=redis
#    build: .
  redis:
    image: redis:3.2
    hostname: redis
    ports:
      - "6379:6379"
  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - "3307:3306"
#    volumes:
#            - "/home/trevor/softwareDev/mySql/docker/init:/docker-entrypoint-initdb.d"
#          - "/home/trevor/softwareDev/mySql/docker/bizwrap/data:/var/lib/mysql"
#          - "/home/trevor/softwareDev/mySql/docker/bizwrap/custom-cnf:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: demo-password
      MYSQL_DATABASE: dockerdemo
      MYSQL_USER: demo-user
      MYSQL_PASSWORD: demo-password
  ha-proxy:
    image: dockercloud/haproxy
    links:
      - spring-web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80