version: '2'
services:
  spring-web:
    depends_on:
      - redis
    image: thomptr/dockerdemo
    links:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=redis
#    build: .
  redis:
    image: redis:3.2
    hostname: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:9.6.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: demo-password
      POSTGRES_USER: demo-user
      POSTGRES_DB: dockerdemo
    volumes:
      - "/home/trevor/softwareDev/databases/postgres/docker-volume:/var/lib/postgresql/data"
      
  ha-proxy:
    image: dockercloud/haproxy
    links:
      - spring-web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80